### ISSUE TITLE
Mistakes in bonuseffects.json

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander#36]
### Lines 311, 319, 327:
English: Change "At the end of this figure's activation" to "At the end of this group's activation"

German: "Am Ende der Aktivierung dieser Figur" --> "Am Ende der Aktivierung dieser Gruppe"

Spanish: "Al final de la activación de esta figura" --> "Al final de la activación de este grupo"

### Line 603
"IMPROVED PENETEATION" should be "IMPROVED PENETRATION"

### Line 629
"Otherwise, it becomse Focused." should be "Otherwise, it becomes Focused."

**Comment by jph33** [comment]
I think in spanish the good translation should be "Al final de la activación de este grupo". No ?
EloFip

**Comment by Noldorion** [comment]
My Spanish is pretty bad, so let's go with your version - I was just extrapolating from other instructions 👍
