### ISSUE TITLE
Improved management of Heroes

### ISSUE THREAD

**Issue by AzzameenF18** [GlowPuff/ImperialCommander#43]
Hi, first of all, the application is really cool (and translated, already a dream). As a suggestion, the left side of the heroes, maybe it could be designed similar to the "Heroes of the Alliance" screen. That is to say, double activation if there are less than 4 heroes, and that all of them have to be exhausted to let the turn pass. This is only as a suggestion, since the heroes are there, to expand the usefulness of the app (also so you can see who has activated, or if you play alone or only two, you can see who is missing the second activation). Greetings and thank you very much!

**Comment by Noldorion** [comment]
Hey there!

Glad that you like the app :-) Just to make sure: There might be a misunderstanding. As of now, there is no hero management at all. The circles at the bottom of the hero portraits are not activation tokens, they are there to toggle them as wounded / healthy. Heroes can't be marked as exhausted in the app currently. Adding this functionality would also mean implementing a way to distribute the additional activation token when you play with three heroes - the Legends of the Alliance app currently distributes it randomly, which would be an option, but another rules change.

**Comment by AzzameenF18** [comment]
Hello, the idea would be to add such management as the official app does (and as an option, you could extend the "AI" so that the enemy groups alter their target to attack the nearest hero already activated, for example ...). I'm also making a revision to the spanish translation (I'm from spain, when I have it ready I'll send it to you).

**Comment by AzzameenF18** [comment]
[Examples.pdf](https://github.com/GlowPuff/ImperialCommander/files/7827813/Examples.pdf)

I attach a PDF with examples of what the interface could look like. Just as an idea

**Comment by Innov2016** [comment]
I really like the app. I think AzzameenF18 suggestion is good as well. The one minor tweak would be that according to the rulebook in a three-player game, the heroes get to choose which hero gets two activations at the end of every round. My suggestions would be as follows: For two heroes, give each hero two activations. For three heroes, give each hero one activation and make a silhouette hero that the players can deactivate when one of the heroes goes twice. For four heroes, each hero gets one activation. This would also mean that you wouldn't need the double activation settings section in the app, it would be set based on player count.

**Comment by GlowPuff** [comment]
I implemented the activation system suggested by Innov2016.  Great idea, thanks!
