### ISSUE TITLE
Improved Spanish translation

### ISSUE THREAD

**Issue by AzzameenF18** [GlowPuff/ImperialCommander#44]
Hello, I attach the files in Spanish with corrections (file Es.zip). I also attach images of the units (you use them in the official App) in case you are interested for a new version (they are round instead of square) (file TOKENS IA.zip). Greetings and I hope it will be useful.
[Es.zip](https://github.com/GlowPuff/ImperialCommander/files/7844196/Es.zip)
[TOKENS IA.zip](https://github.com/GlowPuff/ImperialCommander/files/7844198/TOKENS.IA.zip)

**Comment by AzzameenF18** [comment]
Hello, improved mission texts :-)
[MissionText ES.zip](https://github.com/GlowPuff/ImperialCommander/files/7861952/MissionText.ES.zip)

I have scanned all deployment (and mission) cards to have them in Spanish. The bad thing is that if they are replaced, they are all changed (would it be possible that each language has its own images of the cards?) If you are interested, I can pass the files. Greetings and thanks!

**Comment by GlowPuff** [comment]
Thank you Azzameen!!  I've been really busy with another project for the past couple weeks, but I should be able to get these in soon.

Concerning localized cards - this is something we are actively looking into.  We have a solution, but it'll take time to implement.

**Comment by GlowPuff** [comment]
I got the updated translation AND the circular hero/ally icons in.  Thanks again Azzameen.
