### ISSUE TITLE
Suggestion: Automatically ready activation markers when round ends

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander#45]
After clicking on 'End Round' to start the next round, it would be great if the Activation toggles automatically turn back to their 'green' unactivated side for all Rebel figures that have not withdrawn or been defeated.

https://boardgamegeek.com/thread/2611941/article/39367569#39367569

**Comment by AzzameenF18** [comment]
As a complement to this idea, it could also be put that until the activations of the heroes are exhausted, the turn will not pass (as it happens with the enemies)

**Comment by Noldorion** [comment]
> As a complement to this idea, it could also be put that until the activations of the heroes are exhausted, the turn will not pass (as it happens with the enemies)

I'd would not recommend that. The suggestion is good, but while enemy activations are pretty much mandatory (otherwise there's little reason to use the app), using the Rebel activation token system is optional. People still preferring to use physical tokens to track their activations would have to click 4-6 icons every time they wanted to end the round, which would be annoying.

**Comment by AzzameenF18** [comment]
Just like putting the option of activating the heroes in the app or physically, I don't know, it's just to give the idea one more turn. As I said, it is talk for talk.  greetings and thanks for your time. Thanks you!!!
