### ISSUE TITLE
Bug: enemy deployment

### ISSUE THREAD

**Issue by philsuess** [GlowPuff/ImperialCommander#50]
Enemies deployed are always a Nexu and three droids, no matter what mission is chosen.

This is using v1.0.21 on Android.

**Comment by Noldorion** [comment]
Addendum: This concerns the INITIAL groups. The RESERVED groups are also always the groups from "A New Threat", regardless of the selected mission. It probably has something to do with not loading the mission presets correctly.

Confirmed on Windows.

**Comment by GlowPuff** [comment]
Ugh, yes I'm seeing it - working on it.

**Comment by GlowPuff** [comment]
Nailed it, fixed.
