### ISSUE TITLE
Action icon missing in ally deployment cards

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ImperialCommander#51]
In the dynamic deployment cards, the action icon <img src="https://raw.githubusercontent.com/Noldorion/IA-LORAI-App/master/Documentation/Icons/Action.JPG" width="20"> is not displayed correctly, it only shows the {A}.

This occurs in ally deployment cards. (The enemy cards probably don't have action icons anymore.)

![grafik](https://user-images.githubusercontent.com/67169098/156149539-ca7dcd4e-6be1-46d2-bede-cba0c7faf99c.png)

Same for the surge icon, so it probably doesn't display the icons in the ability names correctly :)

![grafik](https://user-images.githubusercontent.com/67169098/156150376-601ec3fd-5e91-400d-8397-a986f6cc5262.png)

**Comment by GlowPuff** [comment]
got it, fixed!
